# learn about yml
version: "3.8"
services:
  backend:
    image: "afquinon/springboot-react-fullstack:3.9.2021.1.50.57"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev